# Generated by Django 6.1.1 on 2026-09-25 12:15

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Công ty')),
                ('status', models.CharField(choices=[('lead', 'Tiềm năng'), ('caring', 'Đang chăm sóc'), ('customer', 'Đã mua hàng'), ('churned', 'Đã rời bỏ')], default='lead', max_length=20, verbose_name='Trạng thái')),
                ('source', models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook'), ('referral', 'Giới thiệu'), ('other', 'Khác')], default='website', max_length=20, verbose_name='Nguồn khách')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Điện thoại'), ('chat', 'Chat'), ('in_person', 'Trực tiếp')], default='email', max_length=20, verbose_name='Kênh')),
                ('customer_message', models.TextField(verbose_name='Tin nhắn của khách')),
                ('ai_suggested_reply', models.TextField(blank=True, verbose_name='Gợi ý phản hồi của AI')),
                ('final_reply', models.TextField(blank=True, verbose_name='Phản hồi đã gửi')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='Có dùng AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.customer', verbose_name='Khách hàng')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên xử lý')),
            ],
            options={
                'verbose_name': 'Lịch sử tương tác',
                'verbose_name_plural': 'Lịch sử tương tác',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã đơn')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Huỷ')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('product_name', models.CharField(max_length=200, verbose_name='Sản phẩm / dịch vụ')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Đơn giá (VNĐ)')),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.order')),
            ],
            options={
                'verbose_name': 'Dòng sản phẩm',
                'verbose_name_plural': 'Dòng sản phẩm',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
