# Generated by Django 6.1.1 on 2026-09-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_ai_classify_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ai_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='AI đã phân tích'),
        ),
    ]
